# Generated by Django 3.0.5 on 2020-09-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20200912_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
    ]
