# Generated by Django 3.0.5 on 2020-09-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_remove_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='liscence_no',
            new_name='licence_no',
        ),
    ]
